version: '3'
services:
    api:
        build: .
        volumes:
            - ./:/go/src/github.com/naoki-kishi/go-api-sample
        ports:
            - '8080:8080'
        depends_on:
            - db
        command: sh -c "./wait-for-it.sh db:3306;fresh;"
    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        volumes:
            - ./db/mysql_init:/docker-entrypoint-initdb.d
            - ./db/mysql_data:/var/lib/mysql
            - ./db/config/charset.cnf:/etc/mysql/conf.d/charset.cnf

        environment:
            MYSQL_DATABASE: go-api
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
