# Reference : https://qiita.com/po3rin/items/9acd41ef428436335c97
version: '3'
services:
    app:
        build: .
        volumes:
            - ./:/go/src/github.com/naoki-kishi/go-api-sample
        ports:
            - '8083:8083'
